import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SidebarEnglish from "./components/SidebarEnglish";
import SidebarHindi from "./components/SidebarHindi";
import MobileSidebar from "./components/MobileSidebar";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Mobile Sidebar - Only visible on mobile */}
        <MobileSidebar />

          {/* Desktop Sidebars - Hidden on mobile */}

          {/* Main Content */}
          <main className="flex-1">
            {children}
          </main>

          {/* Desktop Hindi Sidebar - Hidden on mobile */}
  

        {/* Footer - Only visible on desktop */}
      </body>
    </html>
  );
}
